version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
